-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1.1 (lin64) Build 6233196 Thu Sep 11 21:27:11 MDT 2025
-- Date        : Thu Jan 22 16:08:07 2026
-- Host        : ece-linlabsrv01 running 64-bit Red Hat Enterprise Linux release 8.10 (Ootpa)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu3eg-sbva484-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_a_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_a_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_a_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_a_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_a_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_a_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_a_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_ARREADY : in STD_LOGIC;
    m_axi_a_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_a_ARVALID : out STD_LOGIC;
    m_axi_a_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_a_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_a_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_a_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_a_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_a_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_a_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_AWREADY : in STD_LOGIC;
    m_axi_a_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_a_AWVALID : out STD_LOGIC;
    m_axi_a_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_a_BREADY : out STD_LOGIC;
    m_axi_a_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_a_BVALID : in STD_LOGIC;
    m_axi_a_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_a_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_a_RLAST : in STD_LOGIC;
    m_axi_a_RREADY : out STD_LOGIC;
    m_axi_a_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_a_RVALID : in STD_LOGIC;
    m_axi_a_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_a_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_a_WLAST : out STD_LOGIC;
    m_axi_a_WREADY : in STD_LOGIC;
    m_axi_a_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_a_WVALID : out STD_LOGIC;
    m_axi_b_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_b_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_b_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_ARREADY : in STD_LOGIC;
    m_axi_b_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_ARVALID : out STD_LOGIC;
    m_axi_b_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_b_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_b_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_AWREADY : in STD_LOGIC;
    m_axi_b_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_AWVALID : out STD_LOGIC;
    m_axi_b_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_BREADY : out STD_LOGIC;
    m_axi_b_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_BVALID : in STD_LOGIC;
    m_axi_b_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_b_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_RLAST : in STD_LOGIC;
    m_axi_b_RREADY : out STD_LOGIC;
    m_axi_b_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_RVALID : in STD_LOGIC;
    m_axi_b_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_b_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_WLAST : out STD_LOGIC;
    m_axi_b_WREADY : in STD_LOGIC;
    m_axi_b_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_WVALID : out STD_LOGIC;
    m_axi_sum_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_sum_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_sum_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_sum_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_sum_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_sum_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_sum_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_ARREADY : in STD_LOGIC;
    m_axi_sum_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_sum_ARVALID : out STD_LOGIC;
    m_axi_sum_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_sum_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_sum_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_sum_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_sum_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_sum_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_sum_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_AWREADY : in STD_LOGIC;
    m_axi_sum_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_sum_AWVALID : out STD_LOGIC;
    m_axi_sum_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_sum_BREADY : out STD_LOGIC;
    m_axi_sum_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_sum_BVALID : in STD_LOGIC;
    m_axi_sum_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_sum_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_sum_RLAST : in STD_LOGIC;
    m_axi_sum_RREADY : out STD_LOGIC;
    m_axi_sum_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_sum_RVALID : in STD_LOGIC;
    m_axi_sum_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_sum_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_sum_WLAST : out STD_LOGIC;
    m_axi_sum_WREADY : in STD_LOGIC;
    m_axi_sum_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_sum_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,top_kernel,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,top_kernel,{x_ipProduct=Vivado 2025.1.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=top_kernel,x_ipVersion=1.0,x_ipCoreRevision=2114447405,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_A_ID_WIDTH=1,C_M_AXI_A_ADDR_WIDTH=64,C_M_AXI_A_DATA_WIDTH=32,C_M_AXI_A_AWUSER_WIDTH=1,C_M_AXI_A_ARUSER_WIDTH=1,C_M_AXI_A_WUSER_WIDTH=1,C_M_AXI_A_RUSER_WIDTH=1,C_M_AXI_A_BUSER_WIDTH=1,C_M_AXI_A_USER_VALUE=0x00000000,C_M_AXI_A_PROT_VALUE=000,C_M_AXI_A_CACHE_VALUE=0011,C_M_AXI_B_ID_WIDTH=1,C_M_AXI_B_ADDR_WIDTH=64,C_M_AXI_B_DATA_WIDTH=32,C_M_AXI_B_AWUSER_WIDTH=1,C_M_AXI_B_ARUSER_WIDTH=1,C_M_AXI_B_WUSER_WIDTH=1,C_M_AXI_B_RUSER_WIDTH=1,C_M_AXI_B_BUSER_WIDTH=1,C_M_AXI_B_USER_VALUE=0x00000000,C_M_AXI_B_PROT_VALUE=000,C_M_AXI_B_CACHE_VALUE=0011,C_M_AXI_SUM_ID_WIDTH=1,C_M_AXI_SUM_ADDR_WIDTH=64,C_M_AXI_SUM_DATA_WIDTH=32,C_M_AXI_SUM_AWUSER_WIDTH=1,C_M_AXI_SUM_ARUSER_WIDTH=1,C_M_AXI_SUM_WUSER_WIDTH=1,C_M_AXI_SUM_RUSER_WIDTH=1,C_M_AXI_SUM_BUSER_WIDTH=1,C_M_AXI_SUM_USER_VALUE=0x00000000,C_M_AXI_SUM_PROT_VALUE=000,C_M_AXI_SUM_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_a_ARADDR[63:0],m_axi_a_ARBURST[1:0],m_axi_a_ARCACHE[3:0],m_axi_a_ARID[0:0],m_axi_a_ARLEN[7:0],m_axi_a_ARLOCK[1:0],m_axi_a_ARPROT[2:0],m_axi_a_ARQOS[3:0],m_axi_a_ARREADY,m_axi_a_ARREGION[3:0],m_axi_a_ARSIZE[2:0],m_axi_a_ARVALID,m_axi_a_AWADDR[63:0],m_axi_a_AWBURST[1:0],m_axi_a_AWCACHE[3:0],m_axi_a_AWID[0:0],m_axi_a_AWLEN[7:0],m_axi_a_AWLOCK[1:0],m_axi_a_AWPROT[2:0],m_axi_a_AWQOS[3:0],m_axi_a_AWREADY,m_axi_a_AWREGION[3:0],m_axi_a_AWSIZE[2:0],m_axi_a_AWVALID,m_axi_a_BID[0:0],m_axi_a_BREADY,m_axi_a_BRESP[1:0],m_axi_a_BVALID,m_axi_a_RDATA[31:0],m_axi_a_RID[0:0],m_axi_a_RLAST,m_axi_a_RREADY,m_axi_a_RRESP[1:0],m_axi_a_RVALID,m_axi_a_WDATA[31:0],m_axi_a_WID[0:0],m_axi_a_WLAST,m_axi_a_WREADY,m_axi_a_WSTRB[3:0],m_axi_a_WVALID,m_axi_b_ARADDR[63:0],m_axi_b_ARBURST[1:0],m_axi_b_ARCACHE[3:0],m_axi_b_ARID[0:0],m_axi_b_ARLEN[7:0],m_axi_b_ARLOCK[1:0],m_axi_b_ARPROT[2:0],m_axi_b_ARQOS[3:0],m_axi_b_ARREADY,m_axi_b_ARREGION[3:0],m_axi_b_ARSIZE[2:0],m_axi_b_ARVALID,m_axi_b_AWADDR[63:0],m_axi_b_AWBURST[1:0],m_axi_b_AWCACHE[3:0],m_axi_b_AWID[0:0],m_axi_b_AWLEN[7:0],m_axi_b_AWLOCK[1:0],m_axi_b_AWPROT[2:0],m_axi_b_AWQOS[3:0],m_axi_b_AWREADY,m_axi_b_AWREGION[3:0],m_axi_b_AWSIZE[2:0],m_axi_b_AWVALID,m_axi_b_BID[0:0],m_axi_b_BREADY,m_axi_b_BRESP[1:0],m_axi_b_BVALID,m_axi_b_RDATA[31:0],m_axi_b_RID[0:0],m_axi_b_RLAST,m_axi_b_RREADY,m_axi_b_RRESP[1:0],m_axi_b_RVALID,m_axi_b_WDATA[31:0],m_axi_b_WID[0:0],m_axi_b_WLAST,m_axi_b_WREADY,m_axi_b_WSTRB[3:0],m_axi_b_WVALID,m_axi_sum_ARADDR[63:0],m_axi_sum_ARBURST[1:0],m_axi_sum_ARCACHE[3:0],m_axi_sum_ARID[0:0],m_axi_sum_ARLEN[7:0],m_axi_sum_ARLOCK[1:0],m_axi_sum_ARPROT[2:0],m_axi_sum_ARQOS[3:0],m_axi_sum_ARREADY,m_axi_sum_ARREGION[3:0],m_axi_sum_ARSIZE[2:0],m_axi_sum_ARVALID,m_axi_sum_AWADDR[63:0],m_axi_sum_AWBURST[1:0],m_axi_sum_AWCACHE[3:0],m_axi_sum_AWID[0:0],m_axi_sum_AWLEN[7:0],m_axi_sum_AWLOCK[1:0],m_axi_sum_AWPROT[2:0],m_axi_sum_AWQOS[3:0],m_axi_sum_AWREADY,m_axi_sum_AWREGION[3:0],m_axi_sum_AWSIZE[2:0],m_axi_sum_AWVALID,m_axi_sum_BID[0:0],m_axi_sum_BREADY,m_axi_sum_BRESP[1:0],m_axi_sum_BVALID,m_axi_sum_RDATA[31:0],m_axi_sum_RID[0:0],m_axi_sum_RLAST,m_axi_sum_RREADY,m_axi_sum_RRESP[1:0],m_axi_sum_RVALID,m_axi_sum_WDATA[31:0],m_axi_sum_WID[0:0],m_axi_sum_WLAST,m_axi_sum_WREADY,m_axi_sum_WSTRB[3:0],m_axi_sum_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000.0, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_a:m_axi_b:m_axi_sum, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000.0, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_a_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARADDR";
  attribute X_INTERFACE_MODE of m_axi_a_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_a_ARADDR : signal is "XIL_INTERFACENAME m_axi_a, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_a_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARBURST";
  attribute X_INTERFACE_INFO of m_axi_a_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_a_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARID";
  attribute X_INTERFACE_INFO of m_axi_a_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARLEN";
  attribute X_INTERFACE_INFO of m_axi_a_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_a_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARPROT";
  attribute X_INTERFACE_INFO of m_axi_a_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARQOS";
  attribute X_INTERFACE_INFO of m_axi_a_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARREADY";
  attribute X_INTERFACE_INFO of m_axi_a_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARREGION";
  attribute X_INTERFACE_INFO of m_axi_a_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_a_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a ARVALID";
  attribute X_INTERFACE_INFO of m_axi_a_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWADDR";
  attribute X_INTERFACE_INFO of m_axi_a_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWBURST";
  attribute X_INTERFACE_INFO of m_axi_a_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_a_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWID";
  attribute X_INTERFACE_INFO of m_axi_a_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWLEN";
  attribute X_INTERFACE_INFO of m_axi_a_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_a_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWPROT";
  attribute X_INTERFACE_INFO of m_axi_a_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWQOS";
  attribute X_INTERFACE_INFO of m_axi_a_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWREADY";
  attribute X_INTERFACE_INFO of m_axi_a_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWREGION";
  attribute X_INTERFACE_INFO of m_axi_a_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_a_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a AWVALID";
  attribute X_INTERFACE_INFO of m_axi_a_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a BID";
  attribute X_INTERFACE_INFO of m_axi_a_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_a BREADY";
  attribute X_INTERFACE_INFO of m_axi_a_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_a BRESP";
  attribute X_INTERFACE_INFO of m_axi_a_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a BVALID";
  attribute X_INTERFACE_INFO of m_axi_a_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_a RDATA";
  attribute X_INTERFACE_INFO of m_axi_a_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a RID";
  attribute X_INTERFACE_INFO of m_axi_a_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_a RLAST";
  attribute X_INTERFACE_INFO of m_axi_a_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_a RREADY";
  attribute X_INTERFACE_INFO of m_axi_a_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_a RRESP";
  attribute X_INTERFACE_INFO of m_axi_a_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a RVALID";
  attribute X_INTERFACE_INFO of m_axi_a_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_a WDATA";
  attribute X_INTERFACE_INFO of m_axi_a_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a WID";
  attribute X_INTERFACE_INFO of m_axi_a_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_a WLAST";
  attribute X_INTERFACE_INFO of m_axi_a_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_a WREADY";
  attribute X_INTERFACE_INFO of m_axi_a_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_a WSTRB";
  attribute X_INTERFACE_INFO of m_axi_a_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_a WVALID";
  attribute X_INTERFACE_INFO of m_axi_b_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARADDR";
  attribute X_INTERFACE_MODE of m_axi_b_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_b_ARADDR : signal is "XIL_INTERFACENAME m_axi_b, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_b_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARBURST";
  attribute X_INTERFACE_INFO of m_axi_b_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_b_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARID";
  attribute X_INTERFACE_INFO of m_axi_b_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARLEN";
  attribute X_INTERFACE_INFO of m_axi_b_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_b_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARPROT";
  attribute X_INTERFACE_INFO of m_axi_b_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARQOS";
  attribute X_INTERFACE_INFO of m_axi_b_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARREADY";
  attribute X_INTERFACE_INFO of m_axi_b_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARREGION";
  attribute X_INTERFACE_INFO of m_axi_b_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_b_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b ARVALID";
  attribute X_INTERFACE_INFO of m_axi_b_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWADDR";
  attribute X_INTERFACE_INFO of m_axi_b_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWBURST";
  attribute X_INTERFACE_INFO of m_axi_b_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_b_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWID";
  attribute X_INTERFACE_INFO of m_axi_b_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWLEN";
  attribute X_INTERFACE_INFO of m_axi_b_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_b_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWPROT";
  attribute X_INTERFACE_INFO of m_axi_b_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWQOS";
  attribute X_INTERFACE_INFO of m_axi_b_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWREADY";
  attribute X_INTERFACE_INFO of m_axi_b_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWREGION";
  attribute X_INTERFACE_INFO of m_axi_b_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_b_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b AWVALID";
  attribute X_INTERFACE_INFO of m_axi_b_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b BID";
  attribute X_INTERFACE_INFO of m_axi_b_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b BREADY";
  attribute X_INTERFACE_INFO of m_axi_b_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_b BRESP";
  attribute X_INTERFACE_INFO of m_axi_b_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b BVALID";
  attribute X_INTERFACE_INFO of m_axi_b_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_b RDATA";
  attribute X_INTERFACE_INFO of m_axi_b_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b RID";
  attribute X_INTERFACE_INFO of m_axi_b_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b RLAST";
  attribute X_INTERFACE_INFO of m_axi_b_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b RREADY";
  attribute X_INTERFACE_INFO of m_axi_b_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_b RRESP";
  attribute X_INTERFACE_INFO of m_axi_b_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b RVALID";
  attribute X_INTERFACE_INFO of m_axi_b_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_b WDATA";
  attribute X_INTERFACE_INFO of m_axi_b_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b WID";
  attribute X_INTERFACE_INFO of m_axi_b_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b WLAST";
  attribute X_INTERFACE_INFO of m_axi_b_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b WREADY";
  attribute X_INTERFACE_INFO of m_axi_b_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_b WSTRB";
  attribute X_INTERFACE_INFO of m_axi_b_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b WVALID";
  attribute X_INTERFACE_INFO of m_axi_sum_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARADDR";
  attribute X_INTERFACE_MODE of m_axi_sum_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_sum_ARADDR : signal is "XIL_INTERFACENAME m_axi_sum, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_sum_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARBURST";
  attribute X_INTERFACE_INFO of m_axi_sum_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_sum_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARID";
  attribute X_INTERFACE_INFO of m_axi_sum_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARLEN";
  attribute X_INTERFACE_INFO of m_axi_sum_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_sum_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARPROT";
  attribute X_INTERFACE_INFO of m_axi_sum_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARQOS";
  attribute X_INTERFACE_INFO of m_axi_sum_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARREADY";
  attribute X_INTERFACE_INFO of m_axi_sum_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARREGION";
  attribute X_INTERFACE_INFO of m_axi_sum_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_sum_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum ARVALID";
  attribute X_INTERFACE_INFO of m_axi_sum_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWADDR";
  attribute X_INTERFACE_INFO of m_axi_sum_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWBURST";
  attribute X_INTERFACE_INFO of m_axi_sum_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_sum_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWID";
  attribute X_INTERFACE_INFO of m_axi_sum_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWLEN";
  attribute X_INTERFACE_INFO of m_axi_sum_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_sum_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWPROT";
  attribute X_INTERFACE_INFO of m_axi_sum_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWQOS";
  attribute X_INTERFACE_INFO of m_axi_sum_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWREADY";
  attribute X_INTERFACE_INFO of m_axi_sum_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWREGION";
  attribute X_INTERFACE_INFO of m_axi_sum_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_sum_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum AWVALID";
  attribute X_INTERFACE_INFO of m_axi_sum_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum BID";
  attribute X_INTERFACE_INFO of m_axi_sum_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum BREADY";
  attribute X_INTERFACE_INFO of m_axi_sum_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum BRESP";
  attribute X_INTERFACE_INFO of m_axi_sum_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum BVALID";
  attribute X_INTERFACE_INFO of m_axi_sum_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum RDATA";
  attribute X_INTERFACE_INFO of m_axi_sum_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum RID";
  attribute X_INTERFACE_INFO of m_axi_sum_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum RLAST";
  attribute X_INTERFACE_INFO of m_axi_sum_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum RREADY";
  attribute X_INTERFACE_INFO of m_axi_sum_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum RRESP";
  attribute X_INTERFACE_INFO of m_axi_sum_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum RVALID";
  attribute X_INTERFACE_INFO of m_axi_sum_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum WDATA";
  attribute X_INTERFACE_INFO of m_axi_sum_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum WID";
  attribute X_INTERFACE_INFO of m_axi_sum_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum WLAST";
  attribute X_INTERFACE_INFO of m_axi_sum_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum WREADY";
  attribute X_INTERFACE_INFO of m_axi_sum_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum WSTRB";
  attribute X_INTERFACE_INFO of m_axi_sum_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_sum WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "top_kernel,Vivado 2025.1.1";
begin
end;
