// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=117,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=2722,HLS_SYN_LUT=2625,HLS_VERSION=2025_1_1}" *)

module top_kernel (
        ap_clk,
        ap_rst_n,
        m_axi_a_AWVALID,
        m_axi_a_AWREADY,
        m_axi_a_AWADDR,
        m_axi_a_AWID,
        m_axi_a_AWLEN,
        m_axi_a_AWSIZE,
        m_axi_a_AWBURST,
        m_axi_a_AWLOCK,
        m_axi_a_AWCACHE,
        m_axi_a_AWPROT,
        m_axi_a_AWQOS,
        m_axi_a_AWREGION,
        m_axi_a_AWUSER,
        m_axi_a_WVALID,
        m_axi_a_WREADY,
        m_axi_a_WDATA,
        m_axi_a_WSTRB,
        m_axi_a_WLAST,
        m_axi_a_WID,
        m_axi_a_WUSER,
        m_axi_a_ARVALID,
        m_axi_a_ARREADY,
        m_axi_a_ARADDR,
        m_axi_a_ARID,
        m_axi_a_ARLEN,
        m_axi_a_ARSIZE,
        m_axi_a_ARBURST,
        m_axi_a_ARLOCK,
        m_axi_a_ARCACHE,
        m_axi_a_ARPROT,
        m_axi_a_ARQOS,
        m_axi_a_ARREGION,
        m_axi_a_ARUSER,
        m_axi_a_RVALID,
        m_axi_a_RREADY,
        m_axi_a_RDATA,
        m_axi_a_RLAST,
        m_axi_a_RID,
        m_axi_a_RUSER,
        m_axi_a_RRESP,
        m_axi_a_BVALID,
        m_axi_a_BREADY,
        m_axi_a_BRESP,
        m_axi_a_BID,
        m_axi_a_BUSER,
        m_axi_b_AWVALID,
        m_axi_b_AWREADY,
        m_axi_b_AWADDR,
        m_axi_b_AWID,
        m_axi_b_AWLEN,
        m_axi_b_AWSIZE,
        m_axi_b_AWBURST,
        m_axi_b_AWLOCK,
        m_axi_b_AWCACHE,
        m_axi_b_AWPROT,
        m_axi_b_AWQOS,
        m_axi_b_AWREGION,
        m_axi_b_AWUSER,
        m_axi_b_WVALID,
        m_axi_b_WREADY,
        m_axi_b_WDATA,
        m_axi_b_WSTRB,
        m_axi_b_WLAST,
        m_axi_b_WID,
        m_axi_b_WUSER,
        m_axi_b_ARVALID,
        m_axi_b_ARREADY,
        m_axi_b_ARADDR,
        m_axi_b_ARID,
        m_axi_b_ARLEN,
        m_axi_b_ARSIZE,
        m_axi_b_ARBURST,
        m_axi_b_ARLOCK,
        m_axi_b_ARCACHE,
        m_axi_b_ARPROT,
        m_axi_b_ARQOS,
        m_axi_b_ARREGION,
        m_axi_b_ARUSER,
        m_axi_b_RVALID,
        m_axi_b_RREADY,
        m_axi_b_RDATA,
        m_axi_b_RLAST,
        m_axi_b_RID,
        m_axi_b_RUSER,
        m_axi_b_RRESP,
        m_axi_b_BVALID,
        m_axi_b_BREADY,
        m_axi_b_BRESP,
        m_axi_b_BID,
        m_axi_b_BUSER,
        m_axi_sum_AWVALID,
        m_axi_sum_AWREADY,
        m_axi_sum_AWADDR,
        m_axi_sum_AWID,
        m_axi_sum_AWLEN,
        m_axi_sum_AWSIZE,
        m_axi_sum_AWBURST,
        m_axi_sum_AWLOCK,
        m_axi_sum_AWCACHE,
        m_axi_sum_AWPROT,
        m_axi_sum_AWQOS,
        m_axi_sum_AWREGION,
        m_axi_sum_AWUSER,
        m_axi_sum_WVALID,
        m_axi_sum_WREADY,
        m_axi_sum_WDATA,
        m_axi_sum_WSTRB,
        m_axi_sum_WLAST,
        m_axi_sum_WID,
        m_axi_sum_WUSER,
        m_axi_sum_ARVALID,
        m_axi_sum_ARREADY,
        m_axi_sum_ARADDR,
        m_axi_sum_ARID,
        m_axi_sum_ARLEN,
        m_axi_sum_ARSIZE,
        m_axi_sum_ARBURST,
        m_axi_sum_ARLOCK,
        m_axi_sum_ARCACHE,
        m_axi_sum_ARPROT,
        m_axi_sum_ARQOS,
        m_axi_sum_ARREGION,
        m_axi_sum_ARUSER,
        m_axi_sum_RVALID,
        m_axi_sum_RREADY,
        m_axi_sum_RDATA,
        m_axi_sum_RLAST,
        m_axi_sum_RID,
        m_axi_sum_RUSER,
        m_axi_sum_RRESP,
        m_axi_sum_BVALID,
        m_axi_sum_BREADY,
        m_axi_sum_BRESP,
        m_axi_sum_BID,
        m_axi_sum_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_A_ID_WIDTH = 1;
parameter    C_M_AXI_A_ADDR_WIDTH = 64;
parameter    C_M_AXI_A_DATA_WIDTH = 32;
parameter    C_M_AXI_A_AWUSER_WIDTH = 1;
parameter    C_M_AXI_A_ARUSER_WIDTH = 1;
parameter    C_M_AXI_A_WUSER_WIDTH = 1;
parameter    C_M_AXI_A_RUSER_WIDTH = 1;
parameter    C_M_AXI_A_BUSER_WIDTH = 1;
parameter    C_M_AXI_A_USER_VALUE = 0;
parameter    C_M_AXI_A_PROT_VALUE = 0;
parameter    C_M_AXI_A_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_B_ID_WIDTH = 1;
parameter    C_M_AXI_B_ADDR_WIDTH = 64;
parameter    C_M_AXI_B_DATA_WIDTH = 32;
parameter    C_M_AXI_B_AWUSER_WIDTH = 1;
parameter    C_M_AXI_B_ARUSER_WIDTH = 1;
parameter    C_M_AXI_B_WUSER_WIDTH = 1;
parameter    C_M_AXI_B_RUSER_WIDTH = 1;
parameter    C_M_AXI_B_BUSER_WIDTH = 1;
parameter    C_M_AXI_B_USER_VALUE = 0;
parameter    C_M_AXI_B_PROT_VALUE = 0;
parameter    C_M_AXI_B_CACHE_VALUE = 3;
parameter    C_M_AXI_SUM_ID_WIDTH = 1;
parameter    C_M_AXI_SUM_ADDR_WIDTH = 64;
parameter    C_M_AXI_SUM_DATA_WIDTH = 32;
parameter    C_M_AXI_SUM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_SUM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_SUM_WUSER_WIDTH = 1;
parameter    C_M_AXI_SUM_RUSER_WIDTH = 1;
parameter    C_M_AXI_SUM_BUSER_WIDTH = 1;
parameter    C_M_AXI_SUM_USER_VALUE = 0;
parameter    C_M_AXI_SUM_PROT_VALUE = 0;
parameter    C_M_AXI_SUM_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_A_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_B_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_SUM_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_a_AWVALID;
input   m_axi_a_AWREADY;
output  [C_M_AXI_A_ADDR_WIDTH - 1:0] m_axi_a_AWADDR;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_AWID;
output  [7:0] m_axi_a_AWLEN;
output  [2:0] m_axi_a_AWSIZE;
output  [1:0] m_axi_a_AWBURST;
output  [1:0] m_axi_a_AWLOCK;
output  [3:0] m_axi_a_AWCACHE;
output  [2:0] m_axi_a_AWPROT;
output  [3:0] m_axi_a_AWQOS;
output  [3:0] m_axi_a_AWREGION;
output  [C_M_AXI_A_AWUSER_WIDTH - 1:0] m_axi_a_AWUSER;
output   m_axi_a_WVALID;
input   m_axi_a_WREADY;
output  [C_M_AXI_A_DATA_WIDTH - 1:0] m_axi_a_WDATA;
output  [C_M_AXI_A_WSTRB_WIDTH - 1:0] m_axi_a_WSTRB;
output   m_axi_a_WLAST;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_WID;
output  [C_M_AXI_A_WUSER_WIDTH - 1:0] m_axi_a_WUSER;
output   m_axi_a_ARVALID;
input   m_axi_a_ARREADY;
output  [C_M_AXI_A_ADDR_WIDTH - 1:0] m_axi_a_ARADDR;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_ARID;
output  [7:0] m_axi_a_ARLEN;
output  [2:0] m_axi_a_ARSIZE;
output  [1:0] m_axi_a_ARBURST;
output  [1:0] m_axi_a_ARLOCK;
output  [3:0] m_axi_a_ARCACHE;
output  [2:0] m_axi_a_ARPROT;
output  [3:0] m_axi_a_ARQOS;
output  [3:0] m_axi_a_ARREGION;
output  [C_M_AXI_A_ARUSER_WIDTH - 1:0] m_axi_a_ARUSER;
input   m_axi_a_RVALID;
output   m_axi_a_RREADY;
input  [C_M_AXI_A_DATA_WIDTH - 1:0] m_axi_a_RDATA;
input   m_axi_a_RLAST;
input  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_RID;
input  [C_M_AXI_A_RUSER_WIDTH - 1:0] m_axi_a_RUSER;
input  [1:0] m_axi_a_RRESP;
input   m_axi_a_BVALID;
output   m_axi_a_BREADY;
input  [1:0] m_axi_a_BRESP;
input  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_BID;
input  [C_M_AXI_A_BUSER_WIDTH - 1:0] m_axi_a_BUSER;
output   m_axi_b_AWVALID;
input   m_axi_b_AWREADY;
output  [C_M_AXI_B_ADDR_WIDTH - 1:0] m_axi_b_AWADDR;
output  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_AWID;
output  [7:0] m_axi_b_AWLEN;
output  [2:0] m_axi_b_AWSIZE;
output  [1:0] m_axi_b_AWBURST;
output  [1:0] m_axi_b_AWLOCK;
output  [3:0] m_axi_b_AWCACHE;
output  [2:0] m_axi_b_AWPROT;
output  [3:0] m_axi_b_AWQOS;
output  [3:0] m_axi_b_AWREGION;
output  [C_M_AXI_B_AWUSER_WIDTH - 1:0] m_axi_b_AWUSER;
output   m_axi_b_WVALID;
input   m_axi_b_WREADY;
output  [C_M_AXI_B_DATA_WIDTH - 1:0] m_axi_b_WDATA;
output  [C_M_AXI_B_WSTRB_WIDTH - 1:0] m_axi_b_WSTRB;
output   m_axi_b_WLAST;
output  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_WID;
output  [C_M_AXI_B_WUSER_WIDTH - 1:0] m_axi_b_WUSER;
output   m_axi_b_ARVALID;
input   m_axi_b_ARREADY;
output  [C_M_AXI_B_ADDR_WIDTH - 1:0] m_axi_b_ARADDR;
output  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_ARID;
output  [7:0] m_axi_b_ARLEN;
output  [2:0] m_axi_b_ARSIZE;
output  [1:0] m_axi_b_ARBURST;
output  [1:0] m_axi_b_ARLOCK;
output  [3:0] m_axi_b_ARCACHE;
output  [2:0] m_axi_b_ARPROT;
output  [3:0] m_axi_b_ARQOS;
output  [3:0] m_axi_b_ARREGION;
output  [C_M_AXI_B_ARUSER_WIDTH - 1:0] m_axi_b_ARUSER;
input   m_axi_b_RVALID;
output   m_axi_b_RREADY;
input  [C_M_AXI_B_DATA_WIDTH - 1:0] m_axi_b_RDATA;
input   m_axi_b_RLAST;
input  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_RID;
input  [C_M_AXI_B_RUSER_WIDTH - 1:0] m_axi_b_RUSER;
input  [1:0] m_axi_b_RRESP;
input   m_axi_b_BVALID;
output   m_axi_b_BREADY;
input  [1:0] m_axi_b_BRESP;
input  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_BID;
input  [C_M_AXI_B_BUSER_WIDTH - 1:0] m_axi_b_BUSER;
output   m_axi_sum_AWVALID;
input   m_axi_sum_AWREADY;
output  [C_M_AXI_SUM_ADDR_WIDTH - 1:0] m_axi_sum_AWADDR;
output  [C_M_AXI_SUM_ID_WIDTH - 1:0] m_axi_sum_AWID;
output  [7:0] m_axi_sum_AWLEN;
output  [2:0] m_axi_sum_AWSIZE;
output  [1:0] m_axi_sum_AWBURST;
output  [1:0] m_axi_sum_AWLOCK;
output  [3:0] m_axi_sum_AWCACHE;
output  [2:0] m_axi_sum_AWPROT;
output  [3:0] m_axi_sum_AWQOS;
output  [3:0] m_axi_sum_AWREGION;
output  [C_M_AXI_SUM_AWUSER_WIDTH - 1:0] m_axi_sum_AWUSER;
output   m_axi_sum_WVALID;
input   m_axi_sum_WREADY;
output  [C_M_AXI_SUM_DATA_WIDTH - 1:0] m_axi_sum_WDATA;
output  [C_M_AXI_SUM_WSTRB_WIDTH - 1:0] m_axi_sum_WSTRB;
output   m_axi_sum_WLAST;
output  [C_M_AXI_SUM_ID_WIDTH - 1:0] m_axi_sum_WID;
output  [C_M_AXI_SUM_WUSER_WIDTH - 1:0] m_axi_sum_WUSER;
output   m_axi_sum_ARVALID;
input   m_axi_sum_ARREADY;
output  [C_M_AXI_SUM_ADDR_WIDTH - 1:0] m_axi_sum_ARADDR;
output  [C_M_AXI_SUM_ID_WIDTH - 1:0] m_axi_sum_ARID;
output  [7:0] m_axi_sum_ARLEN;
output  [2:0] m_axi_sum_ARSIZE;
output  [1:0] m_axi_sum_ARBURST;
output  [1:0] m_axi_sum_ARLOCK;
output  [3:0] m_axi_sum_ARCACHE;
output  [2:0] m_axi_sum_ARPROT;
output  [3:0] m_axi_sum_ARQOS;
output  [3:0] m_axi_sum_ARREGION;
output  [C_M_AXI_SUM_ARUSER_WIDTH - 1:0] m_axi_sum_ARUSER;
input   m_axi_sum_RVALID;
output   m_axi_sum_RREADY;
input  [C_M_AXI_SUM_DATA_WIDTH - 1:0] m_axi_sum_RDATA;
input   m_axi_sum_RLAST;
input  [C_M_AXI_SUM_ID_WIDTH - 1:0] m_axi_sum_RID;
input  [C_M_AXI_SUM_RUSER_WIDTH - 1:0] m_axi_sum_RUSER;
input  [1:0] m_axi_sum_RRESP;
input   m_axi_sum_BVALID;
output   m_axi_sum_BREADY;
input  [1:0] m_axi_sum_BRESP;
input  [C_M_AXI_SUM_ID_WIDTH - 1:0] m_axi_sum_BID;
input  [C_M_AXI_SUM_BUSER_WIDTH - 1:0] m_axi_sum_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_idle_pp0;
wire    ap_ready;
wire    a_0_AWREADY;
wire    a_0_WREADY;
reg    a_0_ARVALID;
wire    a_0_ARREADY;
wire   [31:0] a_0_ARLEN;
wire    a_0_RVALID;
reg    a_0_RREADY;
wire   [31:0] a_0_RDATA;
wire   [8:0] a_0_RFIFONUM;
wire    a_0_BVALID;
wire    b_0_AWREADY;
wire    b_0_WREADY;
reg    b_0_ARVALID;
wire    b_0_ARREADY;
wire   [31:0] b_0_ARLEN;
wire    b_0_RVALID;
reg    b_0_RREADY;
wire   [31:0] b_0_RDATA;
wire   [8:0] b_0_RFIFONUM;
wire    b_0_BVALID;
reg    sum_0_AWVALID;
wire    sum_0_AWREADY;
wire   [31:0] sum_0_AWLEN;
reg    sum_0_WVALID;
wire    sum_0_WREADY;
wire    sum_0_ARREADY;
wire    sum_0_RVALID;
wire   [31:0] sum_0_RDATA;
wire   [8:0] sum_0_RFIFONUM;
wire    sum_0_BVALID;
reg    sum_0_BREADY;
reg   [0:0] first_iter_0_reg_160;
reg    ap_block_state2_io_grp1;
reg    ap_block_state10_pp0_stage0_iter9_grp1;
reg   [0:0] first_iter_0_reg_160_pp0_iter9_reg;
reg    ap_block_state11_io_grp1;
reg   [0:0] icmp_ln11_reg_283;
reg   [0:0] icmp_ln11_reg_283_pp0_iter15_reg;
reg    ap_block_state17_pp0_stage0_iter16_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln11_fu_190_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] a_r;
wire   [63:0] b_r;
wire   [63:0] sum_r;
reg    a_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    a_blk_n_R;
reg    b_blk_n_AR;
reg    b_blk_n_R;
reg    sum_blk_n_AW;
reg    sum_blk_n_W;
reg    sum_blk_n_B;
reg   [0:0] first_iter_0_reg_160_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] first_iter_0_reg_160_pp0_iter2_reg;
reg   [0:0] first_iter_0_reg_160_pp0_iter3_reg;
reg   [0:0] first_iter_0_reg_160_pp0_iter4_reg;
reg   [0:0] first_iter_0_reg_160_pp0_iter5_reg;
reg   [0:0] first_iter_0_reg_160_pp0_iter6_reg;
reg   [0:0] first_iter_0_reg_160_pp0_iter7_reg;
reg   [0:0] first_iter_0_reg_160_pp0_iter8_reg;
reg   [63:0] sum_r_read_reg_268;
reg   [63:0] sum_r_read_reg_268_pp0_iter1_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter2_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter3_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter4_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter5_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter6_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter7_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter8_reg;
reg   [63:0] sum_r_read_reg_268_pp0_iter9_reg;
reg   [63:0] b_r_read_reg_273;
reg   [63:0] a_r_read_reg_278;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln11_reg_283_pp0_iter1_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter2_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter3_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter4_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter5_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter6_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter7_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter8_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter9_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter10_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter11_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter12_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter13_reg;
reg   [0:0] icmp_ln11_reg_283_pp0_iter14_reg;
reg  signed [31:0] a_addr_read_reg_299;
reg  signed [31:0] b_addr_read_reg_304;
wire   [31:0] mul_ln12_fu_172_p2;
reg   [31:0] mul_ln12_reg_315;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] sext_ln11_fu_210_p1;
wire   [63:0] sext_ln11_1_fu_230_p1;
wire   [63:0] sext_ln11_2_fu_250_p1;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [6:0] i1_fu_94;
wire   [6:0] i_fu_184_p2;
reg   [6:0] ap_sig_allocacmp_i1_load;
wire   [61:0] trunc_ln_fu_201_p4;
wire   [61:0] trunc_ln11_1_fu_221_p4;
wire   [61:0] trunc_ln11_2_fu_241_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_796;
reg    ap_condition_681;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 i1_fu_94 = 7'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a_r(a_r),
    .b_r(b_r),
    .sum_r(sum_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

top_kernel_a_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_A_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_A_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_A_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_A_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_A_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_A_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_A_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_A_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_A_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_A_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_A_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
a_m_axi_U(
    .AWVALID(m_axi_a_AWVALID),
    .AWREADY(m_axi_a_AWREADY),
    .AWADDR(m_axi_a_AWADDR),
    .AWID(m_axi_a_AWID),
    .AWLEN(m_axi_a_AWLEN),
    .AWSIZE(m_axi_a_AWSIZE),
    .AWBURST(m_axi_a_AWBURST),
    .AWLOCK(m_axi_a_AWLOCK),
    .AWCACHE(m_axi_a_AWCACHE),
    .AWPROT(m_axi_a_AWPROT),
    .AWQOS(m_axi_a_AWQOS),
    .AWREGION(m_axi_a_AWREGION),
    .AWUSER(m_axi_a_AWUSER),
    .WVALID(m_axi_a_WVALID),
    .WREADY(m_axi_a_WREADY),
    .WDATA(m_axi_a_WDATA),
    .WSTRB(m_axi_a_WSTRB),
    .WLAST(m_axi_a_WLAST),
    .WID(m_axi_a_WID),
    .WUSER(m_axi_a_WUSER),
    .ARVALID(m_axi_a_ARVALID),
    .ARREADY(m_axi_a_ARREADY),
    .ARADDR(m_axi_a_ARADDR),
    .ARID(m_axi_a_ARID),
    .ARLEN(m_axi_a_ARLEN),
    .ARSIZE(m_axi_a_ARSIZE),
    .ARBURST(m_axi_a_ARBURST),
    .ARLOCK(m_axi_a_ARLOCK),
    .ARCACHE(m_axi_a_ARCACHE),
    .ARPROT(m_axi_a_ARPROT),
    .ARQOS(m_axi_a_ARQOS),
    .ARREGION(m_axi_a_ARREGION),
    .ARUSER(m_axi_a_ARUSER),
    .RVALID(m_axi_a_RVALID),
    .RREADY(m_axi_a_RREADY),
    .RDATA(m_axi_a_RDATA),
    .RLAST(m_axi_a_RLAST),
    .RID(m_axi_a_RID),
    .RUSER(m_axi_a_RUSER),
    .RRESP(m_axi_a_RRESP),
    .BVALID(m_axi_a_BVALID),
    .BREADY(m_axi_a_BREADY),
    .BRESP(m_axi_a_BRESP),
    .BID(m_axi_a_BID),
    .BUSER(m_axi_a_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(a_0_ARVALID),
    .I_CH0_ARREADY(a_0_ARREADY),
    .I_CH0_ARADDR(sext_ln11_fu_210_p1),
    .I_CH0_ARLEN(a_0_ARLEN),
    .I_CH0_RVALID(a_0_RVALID),
    .I_CH0_RREADY(a_0_RREADY),
    .I_CH0_RDATA(a_0_RDATA),
    .I_CH0_RFIFONUM(a_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(a_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(a_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(a_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

top_kernel_b_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_B_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_B_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_B_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_B_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_B_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_B_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_B_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_B_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_B_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_B_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_B_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
b_m_axi_U(
    .AWVALID(m_axi_b_AWVALID),
    .AWREADY(m_axi_b_AWREADY),
    .AWADDR(m_axi_b_AWADDR),
    .AWID(m_axi_b_AWID),
    .AWLEN(m_axi_b_AWLEN),
    .AWSIZE(m_axi_b_AWSIZE),
    .AWBURST(m_axi_b_AWBURST),
    .AWLOCK(m_axi_b_AWLOCK),
    .AWCACHE(m_axi_b_AWCACHE),
    .AWPROT(m_axi_b_AWPROT),
    .AWQOS(m_axi_b_AWQOS),
    .AWREGION(m_axi_b_AWREGION),
    .AWUSER(m_axi_b_AWUSER),
    .WVALID(m_axi_b_WVALID),
    .WREADY(m_axi_b_WREADY),
    .WDATA(m_axi_b_WDATA),
    .WSTRB(m_axi_b_WSTRB),
    .WLAST(m_axi_b_WLAST),
    .WID(m_axi_b_WID),
    .WUSER(m_axi_b_WUSER),
    .ARVALID(m_axi_b_ARVALID),
    .ARREADY(m_axi_b_ARREADY),
    .ARADDR(m_axi_b_ARADDR),
    .ARID(m_axi_b_ARID),
    .ARLEN(m_axi_b_ARLEN),
    .ARSIZE(m_axi_b_ARSIZE),
    .ARBURST(m_axi_b_ARBURST),
    .ARLOCK(m_axi_b_ARLOCK),
    .ARCACHE(m_axi_b_ARCACHE),
    .ARPROT(m_axi_b_ARPROT),
    .ARQOS(m_axi_b_ARQOS),
    .ARREGION(m_axi_b_ARREGION),
    .ARUSER(m_axi_b_ARUSER),
    .RVALID(m_axi_b_RVALID),
    .RREADY(m_axi_b_RREADY),
    .RDATA(m_axi_b_RDATA),
    .RLAST(m_axi_b_RLAST),
    .RID(m_axi_b_RID),
    .RUSER(m_axi_b_RUSER),
    .RRESP(m_axi_b_RRESP),
    .BVALID(m_axi_b_BVALID),
    .BREADY(m_axi_b_BREADY),
    .BRESP(m_axi_b_BRESP),
    .BID(m_axi_b_BID),
    .BUSER(m_axi_b_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(b_0_ARVALID),
    .I_CH0_ARREADY(b_0_ARREADY),
    .I_CH0_ARADDR(sext_ln11_1_fu_230_p1),
    .I_CH0_ARLEN(b_0_ARLEN),
    .I_CH0_RVALID(b_0_RVALID),
    .I_CH0_RREADY(b_0_RREADY),
    .I_CH0_RDATA(b_0_RDATA),
    .I_CH0_RFIFONUM(b_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(b_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(b_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(b_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

top_kernel_sum_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_SUM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_SUM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_SUM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_SUM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_SUM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_SUM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_SUM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_SUM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_SUM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_SUM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_SUM_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
sum_m_axi_U(
    .AWVALID(m_axi_sum_AWVALID),
    .AWREADY(m_axi_sum_AWREADY),
    .AWADDR(m_axi_sum_AWADDR),
    .AWID(m_axi_sum_AWID),
    .AWLEN(m_axi_sum_AWLEN),
    .AWSIZE(m_axi_sum_AWSIZE),
    .AWBURST(m_axi_sum_AWBURST),
    .AWLOCK(m_axi_sum_AWLOCK),
    .AWCACHE(m_axi_sum_AWCACHE),
    .AWPROT(m_axi_sum_AWPROT),
    .AWQOS(m_axi_sum_AWQOS),
    .AWREGION(m_axi_sum_AWREGION),
    .AWUSER(m_axi_sum_AWUSER),
    .WVALID(m_axi_sum_WVALID),
    .WREADY(m_axi_sum_WREADY),
    .WDATA(m_axi_sum_WDATA),
    .WSTRB(m_axi_sum_WSTRB),
    .WLAST(m_axi_sum_WLAST),
    .WID(m_axi_sum_WID),
    .WUSER(m_axi_sum_WUSER),
    .ARVALID(m_axi_sum_ARVALID),
    .ARREADY(m_axi_sum_ARREADY),
    .ARADDR(m_axi_sum_ARADDR),
    .ARID(m_axi_sum_ARID),
    .ARLEN(m_axi_sum_ARLEN),
    .ARSIZE(m_axi_sum_ARSIZE),
    .ARBURST(m_axi_sum_ARBURST),
    .ARLOCK(m_axi_sum_ARLOCK),
    .ARCACHE(m_axi_sum_ARCACHE),
    .ARPROT(m_axi_sum_ARPROT),
    .ARQOS(m_axi_sum_ARQOS),
    .ARREGION(m_axi_sum_ARREGION),
    .ARUSER(m_axi_sum_ARUSER),
    .RVALID(m_axi_sum_RVALID),
    .RREADY(m_axi_sum_RREADY),
    .RDATA(m_axi_sum_RDATA),
    .RLAST(m_axi_sum_RLAST),
    .RID(m_axi_sum_RID),
    .RUSER(m_axi_sum_RUSER),
    .RRESP(m_axi_sum_RRESP),
    .BVALID(m_axi_sum_BVALID),
    .BREADY(m_axi_sum_BREADY),
    .BRESP(m_axi_sum_BRESP),
    .BID(m_axi_sum_BID),
    .BUSER(m_axi_sum_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(sum_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(sum_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(sum_0_RDATA),
    .I_CH0_RFIFONUM(sum_0_RFIFONUM),
    .I_CH0_AWVALID(sum_0_AWVALID),
    .I_CH0_AWREADY(sum_0_AWREADY),
    .I_CH0_AWADDR(sext_ln11_2_fu_250_p1),
    .I_CH0_AWLEN(sum_0_AWLEN),
    .I_CH0_WVALID(sum_0_WVALID),
    .I_CH0_WREADY(sum_0_WREADY),
    .I_CH0_WDATA(mul_ln12_reg_315),
    .I_CH0_WSTRB(4'd15),
    .I_CH0_BVALID(sum_0_BVALID),
    .I_CH0_BREADY(sum_0_BREADY)
);

top_kernel_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(b_addr_read_reg_304),
    .din1(a_addr_read_reg_299),
    .dout(mul_ln12_fu_172_p2)
);

top_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter16_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter15_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_796)) begin
            first_iter_0_reg_160 <= 1'd0;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            first_iter_0_reg_160 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_681)) begin
        i1_fu_94 <= i_fu_184_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        a_addr_read_reg_299 <= a_0_RDATA;
        b_addr_read_reg_304 <= b_0_RDATA;
        first_iter_0_reg_160_pp0_iter2_reg <= first_iter_0_reg_160_pp0_iter1_reg;
        first_iter_0_reg_160_pp0_iter3_reg <= first_iter_0_reg_160_pp0_iter2_reg;
        first_iter_0_reg_160_pp0_iter4_reg <= first_iter_0_reg_160_pp0_iter3_reg;
        first_iter_0_reg_160_pp0_iter5_reg <= first_iter_0_reg_160_pp0_iter4_reg;
        first_iter_0_reg_160_pp0_iter6_reg <= first_iter_0_reg_160_pp0_iter5_reg;
        first_iter_0_reg_160_pp0_iter7_reg <= first_iter_0_reg_160_pp0_iter6_reg;
        first_iter_0_reg_160_pp0_iter8_reg <= first_iter_0_reg_160_pp0_iter7_reg;
        first_iter_0_reg_160_pp0_iter9_reg <= first_iter_0_reg_160_pp0_iter8_reg;
        mul_ln12_reg_315 <= mul_ln12_fu_172_p2;
        sum_r_read_reg_268_pp0_iter2_reg <= sum_r_read_reg_268_pp0_iter1_reg;
        sum_r_read_reg_268_pp0_iter3_reg <= sum_r_read_reg_268_pp0_iter2_reg;
        sum_r_read_reg_268_pp0_iter4_reg <= sum_r_read_reg_268_pp0_iter3_reg;
        sum_r_read_reg_268_pp0_iter5_reg <= sum_r_read_reg_268_pp0_iter4_reg;
        sum_r_read_reg_268_pp0_iter6_reg <= sum_r_read_reg_268_pp0_iter5_reg;
        sum_r_read_reg_268_pp0_iter7_reg <= sum_r_read_reg_268_pp0_iter6_reg;
        sum_r_read_reg_268_pp0_iter8_reg <= sum_r_read_reg_268_pp0_iter7_reg;
        sum_r_read_reg_268_pp0_iter9_reg <= sum_r_read_reg_268_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_r_read_reg_278 <= a_r;
        b_r_read_reg_273 <= b_r;
        first_iter_0_reg_160_pp0_iter1_reg <= first_iter_0_reg_160;
        sum_r_read_reg_268 <= sum_r;
        sum_r_read_reg_268_pp0_iter1_reg <= sum_r_read_reg_268;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln11_reg_283_pp0_iter10_reg <= icmp_ln11_reg_283_pp0_iter9_reg;
        icmp_ln11_reg_283_pp0_iter11_reg <= icmp_ln11_reg_283_pp0_iter10_reg;
        icmp_ln11_reg_283_pp0_iter12_reg <= icmp_ln11_reg_283_pp0_iter11_reg;
        icmp_ln11_reg_283_pp0_iter13_reg <= icmp_ln11_reg_283_pp0_iter12_reg;
        icmp_ln11_reg_283_pp0_iter14_reg <= icmp_ln11_reg_283_pp0_iter13_reg;
        icmp_ln11_reg_283_pp0_iter15_reg <= icmp_ln11_reg_283_pp0_iter14_reg;
        icmp_ln11_reg_283_pp0_iter2_reg <= icmp_ln11_reg_283_pp0_iter1_reg;
        icmp_ln11_reg_283_pp0_iter3_reg <= icmp_ln11_reg_283_pp0_iter2_reg;
        icmp_ln11_reg_283_pp0_iter4_reg <= icmp_ln11_reg_283_pp0_iter3_reg;
        icmp_ln11_reg_283_pp0_iter5_reg <= icmp_ln11_reg_283_pp0_iter4_reg;
        icmp_ln11_reg_283_pp0_iter6_reg <= icmp_ln11_reg_283_pp0_iter5_reg;
        icmp_ln11_reg_283_pp0_iter7_reg <= icmp_ln11_reg_283_pp0_iter6_reg;
        icmp_ln11_reg_283_pp0_iter8_reg <= icmp_ln11_reg_283_pp0_iter7_reg;
        icmp_ln11_reg_283_pp0_iter9_reg <= icmp_ln11_reg_283_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln11_reg_283 <= icmp_ln11_fu_190_p2;
        icmp_ln11_reg_283_pp0_iter1_reg <= icmp_ln11_reg_283;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_iter_0_reg_160 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_0_ARVALID = 1'b1;
    end else begin
        a_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        a_0_RREADY = 1'b1;
    end else begin
        a_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_iter_0_reg_160 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_blk_n_AR = m_axi_a_ARREADY;
    end else begin
        a_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        a_blk_n_R = m_axi_a_RVALID;
    end else begin
        a_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln11_fu_190_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter16_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i1_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_iter_0_reg_160 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_0_ARVALID = 1'b1;
    end else begin
        b_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_0_RREADY = 1'b1;
    end else begin
        b_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (first_iter_0_reg_160 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_blk_n_AR = m_axi_b_ARREADY;
    end else begin
        b_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        b_blk_n_R = m_axi_b_RVALID;
    end else begin
        b_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_160_pp0_iter9_reg == 1'd1))) begin
        sum_0_AWVALID = 1'b1;
    end else begin
        sum_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln11_reg_283_pp0_iter15_reg == 1'd1))) begin
        sum_0_BREADY = 1'b1;
    end else begin
        sum_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        sum_0_WVALID = 1'b1;
    end else begin
        sum_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (first_iter_0_reg_160_pp0_iter9_reg == 1'd1))) begin
        sum_blk_n_AW = m_axi_sum_AWREADY;
    end else begin
        sum_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln11_reg_283_pp0_iter15_reg == 1'd1))) begin
        sum_blk_n_B = m_axi_sum_BVALID;
    end else begin
        sum_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        sum_blk_n_W = m_axi_sum_WREADY;
    end else begin
        sum_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_0_ARLEN = 64'd100;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter16_grp1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter16_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (sum_0_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_io_grp1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter16_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (sum_0_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_io_grp1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter16_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (sum_0_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_io_grp1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9_grp1 = ((1'b0 == a_0_RVALID) | (b_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state11_io_grp1 = ((first_iter_0_reg_160_pp0_iter9_reg == 1'd1) & (sum_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter16_grp1 = ((icmp_ln11_reg_283_pp0_iter15_reg == 1'd1) & (sum_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io_grp1 = (((first_iter_0_reg_160 == 1'd1) & (b_0_ARREADY == 1'b0)) | ((1'b0 == a_0_ARREADY) & (first_iter_0_reg_160 == 1'd1)));
end

always @ (*) begin
    ap_condition_681 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_796 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln11_reg_283 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b_0_ARLEN = 64'd100;

assign i_fu_184_p2 = (ap_sig_allocacmp_i1_load + 7'd1);

assign icmp_ln11_fu_190_p2 = ((ap_sig_allocacmp_i1_load == 7'd99) ? 1'b1 : 1'b0);

assign sext_ln11_1_fu_230_p1 = $signed(trunc_ln11_1_fu_221_p4);

assign sext_ln11_2_fu_250_p1 = $signed(trunc_ln11_2_fu_241_p4);

assign sext_ln11_fu_210_p1 = $signed(trunc_ln_fu_201_p4);

assign sum_0_AWLEN = 64'd100;

assign trunc_ln11_1_fu_221_p4 = {{b_r_read_reg_273[63:2]}};

assign trunc_ln11_2_fu_241_p4 = {{sum_r_read_reg_268_pp0_iter9_reg[63:2]}};

assign trunc_ln_fu_201_p4 = {{a_r_read_reg_278[63:2]}};

endmodule //top_kernel
